name: nekonime
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_spinkit: ^5.2.2
  connectivity_plus: ^7.0.0
  fluttertoast: ^8.2.12
  firebase_core: ^4.1.0
  cloud_firestore: ^6.0.1
  carousel_slider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon/nekonime.png"
  min_sdk_android: 28
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon/nekonime.png"

flutter:
  uses-material-design: true
  assets:
    - assets/image/
    - assets/icon/
    - assets/banner/
